FROM node:18 AS builder
WORKDIR /app
COPY expense-tracker/frontend/package*.json .
RUN npm install
COPY expense-tracker/frontend .
RUN npm run build

FROM nginx:latest
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80